feat: implement new and improved diagnosepicker
navikt/syk-dig pull request #304
Opened 2024-08-22 12:50 UTC by karl-run

2024-08-22 14:00 UTC, heinharaldsen approved these changes

2024-08-23 09:16 UTC, nuranes commented on src/components/FormComponents/DiagnosePicker/DiagnosePicker.tsx
> +            <BodyShort className={cn('h-12 flex items-start')}>{text ?? '-'}</BodyShort>
Kan fjerne `cn` her?

```suggestion
            <BodyShort className={'h-12 flex items-start'}>{text ?? '-'}</BodyShort>
```

2024-08-23 09:18 UTC, nuranes commented on src/components/FormComponents/combobox/AkselifiedCombobox.tsx
> +        <Combobox.ComboboxPopover gutter={8} sameWidth className={cn('navds-combobox__list')} {...props}>
```suggestion
        <Combobox.ComboboxPopover gutter={8} sameWidth className={'navds-combobox__list'} {...props}>
```

2024-08-23 11:28 UTC, nuranes requested changes
Oppdaga at eg får Error `Warning: Only plain objects can be passed to Client Components from Server Components. Objects with symbol properties like icpc2 are not supported.` i terminalen når eg søker på diagnosekode lokalt. Ser ut som det skjer kun for icpc2, så noko rusk som burde fiksast?

2024-08-26 11:14 UTC, merged